version: '3.7'

services:
  app:
    container_name: app
    build: app
  
#  iot:
#    container_name: iot
#    build: iot

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - app
      

  postgres:
    container_name: postgres
    build: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: postgres/password.txt
